cookie:
  expiry_days: 30
  key: savethequeen!@
  name: ggdjwt
credentials:
  usernames:
    test1:
      email: test1@naver.com
      failed_login_attempts: 0
      logged_in: true
      name: user1
      password: $2b$12$HrKlRqOrwZDqGKU12pJVUO9PTWwG4EtugQWIXFmLx38UAZO1tmdjO
pre-authorized:
  emails:
  - melsby@gmail.com
